name: credit_capital
description: Attendace system

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



#  location: ^4.4.0

  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  provider: ^6.0.4
  flutter_native_splash: ^2.2.16
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.0.7
  firebase_core: ^2.3.0
  get_it: "7.2.0"
  local_auth: ^2.1.2
  loading_overlay:
  animation_wrappers: ^2.0.0
  fluttertoast: ^8.1.1
  lottie: ^2.0.0
  image_picker: ^0.8.6
  uuid: 3.0.6
  file_support: ^1.0.3+6
  shared_preferences: ^2.0.15
#  geofence_service: ^3.5.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  cached_network_image:



flutter_native_splash:
  color: "#FFFFFF"
  #  background_image: "assets/splash.png"
  image: assets/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

